### ISSUE TITLE
Fix Grammar.

### ISSUE THREAD

**Issue by Kadse1337** [Dytanic/CloudNet#15]
Replace "The information was send to the cloud" with "The information was sent to the cloud". 
Occurrences:
* 18 times in de.dytanic.cloudnet.bridge.internal.command.proxied.CommandCloud.java

Replace "The player doesn't registered" with "The player isn't registered"
Occurrences:
* 6 times in de.dytanic.cloudnet.bridge.internal.command.proxied.CommandPermissions.java

Replace "The group doesn't exists" with "The group doesn't exist"
Occurrences:
* 13 times in de.dytanic.cloudnet.bridge.internal.command.proxied.CommandPermissions.java
 
 These were just 3 examples, the plugin is riddled with grammar and syntax errors. Please either provide a way to configure the messages, or simply improve them.

**Comment by cryoW0lf** [comment]
Wurde im Pullrequest #16 gefixt
