### ISSUE TITLE
Send player to another server via cloudnet api

### ISSUE THREAD

**Issue by LeDennis32** [Dytanic/CloudNet#22]
Hello, I want to send a player to another server on the proxy with the cloudnet api.

I tried this, but it does nothing:
```java
CloudServer cs = CloudServer.getInstance();
CloudPlayer cp = cs.getCachedPlayer(p.getUniqueId());
cp.setServer("SERVERNAME");
```

This plugin is a bukkit/spigot plugin, not bungeecord.
Thanks for answers :smiley:

EDIT: I'm using version _CloudNet PRE 2.1.Pv30F0_

**Comment by Sarsum** [comment]
Hey, 
this should work fine
`CloudPlayer cloudPlayer = CloudAPI.getInstance().getOnlinePlayer(p.getUniqueId());
PlayerExecutorBridge.INSTANCE.sendPlayer(cloudPlayer, "SERVERNAME");`
