### ISSUE TITLE
Ich verstehe diese abfrage nicht, in der ist zwei mal 127.0.0.1

### ISSUE THREAD

**Issue by DevCyntrix** [Dytanic/CloudNet#9]
https://github.com/Dytanic/CloudNet/blob/dc87d7c0891707342cfe09bbf16dd9b40edb9d3d/cloudnet-core/src/main/java/de/dytanic/cloudnetcore/CloudConfig.java#L187

**Comment by RaspiFreak** [comment]
Ich denke mal da sollte wahrscheinlich 127.0.1.1 hin da das in der Zeile 181 ähnlich ist. 😄

https://github.com/Dytanic/CloudNet/blob/dc87d7c0891707342cfe09bbf16dd9b40edb9d3d/cloudnet-core/src/main/java/de/dytanic/cloudnetcore/CloudConfig.java#L181

**Comment by Dytanic** [comment]
@RaspiFreak hat dabei recht. Das war ein Fehler von mir :c

**Comment by Eisphoenix** [comment]
Wurde in fb8b6809d37fad39df92160adc3b4d3b9ac1fdc9 ja gefixt, schließe ich hiermit mal ^^
